### ISSUE TITLE
Archive on Software Heritage

### ISSUE THREAD

**Issue by agitter** [gitter-lab/influenza-pb2#5]
Once the repository contents stabilize, we can request that it is archived at https://archive.softwareheritage.org/save/

**Comment by SidharajYadav** [comment]
Respect Sir,
I'm Siddharaj Yadav a computer engineering undergraduate, Pursuing TE at D Y Patil College under (Pune University).
I am new to open source contribution but I am well aware of Python,Django,HTML and Git& GitHub. I would to contribute to your organization but could you please tell me how to get started? Gsoc
Hoping to hear from you soon
Regards
Siddharaj Yadav
mail- sidharajyadav157@gmail.com
GitHub - SidharajYadav

**Comment by agitter** [comment]
@SidharajYadav please follow the link in my GitHub profile to find my contact information if you would like to discuss general projects.  This GitHub issue pertains to one specific task on one specific code base.

**Comment by SidharajYadav** [comment]
Yes Sir ,
Thank you

**Comment by agitter** [comment]
I created a Software Heritage archive: https://archive.softwareheritage.org/browse/origin/directory/?origin_url=https://github.com/gitter-lab/influenza-pb2&timestamp=2022-11-20T14:22:54.091017%2B00:00

I will leave this issue open because I would like to archive the repository on Zenodo as well.
